<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Client;
use App\Models\User;

class ClientSeeder extends Seeder
{
    public function run(): void
    {
        $adminId = User::where('role', 'admin')->first()?->id;
        
        $clients = [
            [
                'name' => 'John Doe',
                'email' => 'john@example.com',
                'mobile_no' => '+1 555-0101',
                'website' => 'https://johndoe.com',
                'project_link' => 'https://github.com/johndoe/crm',
                'location' => 'New York, USA',
                'technology' => 'Laravel, Vue.js',
                'linkedin' => 'https://linkedin.com/in/johndoe',
                'facebook' => 'https://facebook.com/johndoe',
                'instagram' => 'https://instagram.com/johndoe',
                'youtube' => 'https://youtube.com/@johndoe',
                'x' => 'https://x.com/johndoe',
                'telegram' => '@johndoe_tg',
                'whatsapp' => '+15550101',
                'teams' => 'john.teams@example.com',
                'status' => 'In Progress',
                'assigned_to' => $adminId,
                'last_contacted_date' => now()->subDays(2),
                'follow_up_days' => 7,
                'notes' => 'Looking for a custom CRM solution.'
            ],
            [
                'name' => 'Sarah Smith',
                'email' => 'sarah@techcorp.com',
                'mobile_no' => '+44 20 7946 0958',
                'website' => 'https://techcorp.com',
                'project_link' => 'https://github.com/techcorp',
                'location' => 'London, UK',
                'technology' => 'React, Node.js',
                'linkedin' => 'https://linkedin.com/in/sarahsmith',
                'facebook' => 'https://facebook.com/sarahsmith',
                'instagram' => 'https://instagram.com/sarahsmith',
                'youtube' => 'https://youtube.com/@sarahsmith',
                'x' => 'https://x.com/sarahsmith',
                'telegram' => '@sarahsmith',
                'whatsapp' => '+442079460958',
                'teams' => 'sarah.teams@techcorp.com',
                'status' => 'New',
                'assigned_to' => $adminId,
                'last_contacted_date' => now()->subDays(1),
                'follow_up_days' => 3,
                'notes' => 'Interested in e-commerce migration.'
            ],
            [
                'name' => 'Michael Chen',
                'email' => 'm.chen@asiatech.sg',
                'mobile_no' => '+65 6123 4567',
                'website' => 'https://asiatech.sg',
                'project_link' => 'https://gitlab.com/mchen',
                'location' => 'Singapore',
                'technology' => 'Python, Django',
                'linkedin' => 'https://linkedin.com/in/mchen',
                'facebook' => 'https://facebook.com/mchen',
                'instagram' => 'https://instagram.com/mchen',
                'youtube' => 'https://youtube.com/@mchen',
                'x' => 'https://x.com/mchen',
                'telegram' => '@mchen_sg',
                'whatsapp' => '+6561234567',
                'teams' => 'm.chen@asiatech.sg',
                'status' => 'Follow Up',
                'assigned_to' => $adminId,
                'last_contacted_date' => now()->subDays(5),
                'follow_up_days' => 2,
                'notes' => 'Wants to discuss AI integration.'
            ],
            [
                'name' => 'Elena Rodriguez',
                'email' => 'elena@madridweb.es',
                'mobile_no' => '+34 912 34 56 78',
                'website' => 'https://madridweb.es',
                'project_link' => 'https://github.com/elena',
                'location' => 'Madrid, Spain',
                'technology' => 'WordPress, PHP',
                'linkedin' => 'https://linkedin.com/in/elena',
                'facebook' => 'https://facebook.com/elena',
                'instagram' => 'https://instagram.com/elena',
                'youtube' => 'https://youtube.com/@elena',
                'x' => 'https://x.com/elena',
                'telegram' => '@elena_tg',
                'whatsapp' => '+34912345678',
                'teams' => 'elena.teams@madridweb.es',
                'status' => 'Closed Won',
                'assigned_to' => $adminId,
                'last_contacted_date' => now()->subDays(10),
                'follow_up_days' => 30,
                'notes' => 'Maintenance contract signed.'
            ],
            [
                'name' => 'David Muller',
                'email' => 'd.muller@berlinit.de',
                'mobile_no' => '+49 30 123456',
                'website' => 'https://berlinit.de',
                'project_link' => 'https://bitbucket.org/dmuller',
                'location' => 'Berlin, Germany',
                'technology' => 'Java, Spring Boot',
                'linkedin' => 'https://linkedin.com/in/dmuller',
                'facebook' => 'https://facebook.com/dmuller',
                'instagram' => 'https://instagram.com/dmuller',
                'youtube' => 'https://youtube.com/@dmuller',
                'x' => 'https://x.com/dmuller',
                'telegram' => '@dmuller_berlin',
                'whatsapp' => '+4930123456',
                'teams' => 'david.teams@berlinit.de',
                'status' => 'Contacted',
                'assigned_to' => $adminId,
                'last_contacted_date' => now()->subDays(1),
                'follow_up_days' => 5,
                'notes' => 'Initial inquiry received.'
            ],
            [
                'name' => 'Priya Sharma',
                'email' => 'priya@indiastack.in',
                'mobile_no' => '+91 98765 43210',
                'website' => 'https://indiastack.in',
                'project_link' => 'https://github.com/priya',
                'location' => 'Mumbai, India',
                'technology' => 'React Native, Flutter',
                'linkedin' => 'https://linkedin.com/in/priya',
                'facebook' => 'https://facebook.com/priya',
                'instagram' => 'https://instagram.com/priya',
                'youtube' => 'https://youtube.com/@priya',
                'x' => 'https://x.com/priya',
                'telegram' => '@priya_in',
                'whatsapp' => '+919876543210',
                'teams' => 'priya.teams@indiastack.in',
                'status' => 'In Progress',
                'assigned_to' => $adminId,
                'last_contacted_date' => now()->subDays(3),
                'follow_up_days' => 7,
                'notes' => 'Mobile app project scope under review.'
            ],
            [
                'name' => 'Thomas Wright',
                'email' => 't.wright@austech.com.au',
                'mobile_no' => '+61 2 9876 5432',
                'website' => 'https://austech.com.au',
                'project_link' => 'https://gitlab.com/twright',
                'location' => 'Sydney, Australia',
                'technology' => 'AWS, Serverless',
                'linkedin' => 'https://linkedin.com/in/twright',
                'facebook' => 'https://facebook.com/twright',
                'instagram' => 'https://instagram.com/twright',
                'youtube' => 'https://youtube.com/@twright',
                'x' => 'https://x.com/twright',
                'telegram' => '@twright_au',
                'whatsapp' => '+61298765432',
                'teams' => 'thomas.teams@austech.com.au',
                'status' => 'On Hold',
                'assigned_to' => $adminId,
                'last_contacted_date' => now()->subDays(15),
                'follow_up_days' => 14,
                'notes' => 'Waiting for budget approval.'
            ],
            [
                'name' => 'Sophie Laurent',
                'email' => 's.laurent@parisdev.fr',
                'mobile_no' => '+33 1 23 45 67 89',
                'website' => 'https://parisdev.fr',
                'project_link' => 'https://github.com/slaurent',
                'location' => 'Paris, France',
                'technology' => 'Symfony, MySQL',
                'linkedin' => 'https://linkedin.com/in/slaurent',
                'facebook' => 'https://facebook.com/slaurent',
                'instagram' => 'https://instagram.com/slaurent',
                'youtube' => 'https://youtube.com/@slaurent',
                'x' => 'https://x.com/slaurent',
                'telegram' => '@slaurent_fr',
                'whatsapp' => '+33123456789',
                'teams' => 'sophie.teams@parisdev.fr',
                'status' => 'Follow Up',
                'assigned_to' => $adminId,
                'last_contacted_date' => now()->subDays(4),
                'follow_up_days' => 1,
                'notes' => 'Demo scheduled for next week.'
            ],
            [
                'name' => 'Alex Kim',
                'email' => 'alex.kim@seoultech.kr',
                'mobile_no' => '+82 2-1234-5678',
                'website' => 'https://seoultech.kr',
                'project_link' => 'https://github.com/alexkim',
                'location' => 'Seoul, South Korea',
                'technology' => 'Go, Kubernetes',
                'linkedin' => 'https://linkedin.com/in/alexkim',
                'facebook' => 'https://facebook.com/alexkim',
                'instagram' => 'https://instagram.com/alexkim',
                'youtube' => 'https://youtube.com/@alexkim',
                'x' => 'https://x.com/alexkim',
                'telegram' => '@alexkim_kr',
                'whatsapp' => '+82212345678',
                'teams' => 'alex.teams@seoultech.kr',
                'status' => 'New',
                'assigned_to' => $adminId,
                'last_contacted_date' => now()->subDays(1),
                'follow_up_days' => 2,
                'notes' => 'High priority lead.'
            ],
            [
                'name' => 'Ahmed Mansour',
                'email' => 'ahmed@dubaiweb.ae',
                'mobile_no' => '+971 4 123 4567',
                'website' => 'https://dubaiweb.ae',
                'project_link' => 'https://gitlab.com/ahmedm',
                'location' => 'Dubai, UAE',
                'technology' => 'Angular, .NET',
                'linkedin' => 'https://linkedin.com/in/ahmedm',
                'facebook' => 'https://facebook.com/ahmedm',
                'instagram' => 'https://instagram.com/ahmedm',
                'youtube' => 'https://youtube.com/@ahmedm',
                'x' => 'https://x.com/ahmedm',
                'telegram' => '@ahmedm_uae',
                'whatsapp' => '+97141234567',
                'teams' => 'ahmed.teams@dubaiweb.ae',
                'status' => 'Contacted',
                'assigned_to' => $adminId,
                'last_contacted_date' => now()->subDays(2),
                'follow_up_days' => 4,
                'notes' => 'Discussing enterprise portal.'
            ],
        ];

        foreach ($clients as $clientData) {
            Client::create($clientData);
        }
    }
}
